//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.AddUserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddUserService.IAddService")]
    public interface IAddService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/InsertUser", ReplyAction="http://tempuri.org/IAddService/InsertUserResponse")]
        void InsertUser(int id, string userName, string firstName, string lastName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/InsertUser", ReplyAction="http://tempuri.org/IAddService/InsertUserResponse")]
        System.Threading.Tasks.Task InsertUserAsync(int id, string userName, string firstName, string lastName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/GetOfflineUsers", ReplyAction="http://tempuri.org/IAddService/GetOfflineUsersResponse")]
        Model.User[] GetOfflineUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/GetOfflineUsers", ReplyAction="http://tempuri.org/IAddService/GetOfflineUsersResponse")]
        System.Threading.Tasks.Task<Model.User[]> GetOfflineUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/IsUserExist", ReplyAction="http://tempuri.org/IAddService/IsUserExistResponse")]
        AddService.AddToDict IsUserExist(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddService/IsUserExist", ReplyAction="http://tempuri.org/IAddService/IsUserExistResponse")]
        System.Threading.Tasks.Task<AddService.AddToDict> IsUserExistAsync(string userName, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddServiceChannel : TestClient.AddUserService.IAddService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddServiceClient : System.ServiceModel.ClientBase<TestClient.AddUserService.IAddService>, TestClient.AddUserService.IAddService {
        
        public AddServiceClient() {
        }
        
        public AddServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertUser(int id, string userName, string firstName, string lastName, string password) {
            base.Channel.InsertUser(id, userName, firstName, lastName, password);
        }
        
        public System.Threading.Tasks.Task InsertUserAsync(int id, string userName, string firstName, string lastName, string password) {
            return base.Channel.InsertUserAsync(id, userName, firstName, lastName, password);
        }
        
        public Model.User[] GetOfflineUsers() {
            return base.Channel.GetOfflineUsers();
        }
        
        public System.Threading.Tasks.Task<Model.User[]> GetOfflineUsersAsync() {
            return base.Channel.GetOfflineUsersAsync();
        }
        
        public AddService.AddToDict IsUserExist(string userName, string password) {
            return base.Channel.IsUserExist(userName, password);
        }
        
        public System.Threading.Tasks.Task<AddService.AddToDict> IsUserExistAsync(string userName, string password) {
            return base.Channel.IsUserExistAsync(userName, password);
        }
    }
}
